### ISSUE TITLE
dsc_reboot recommendation causes reboot

### ISSUE THREAD

**Issue by johnf** [puppetlabs/puppetlabs-dsc#267] opened 2016-12-30 03:13 UTC
The dsc_reboot recommendation I've found can be a bit dangerous. If the machine is installing updates in the background then it will be rebooted at the next puppet run instead of at the scheduled spot at say 2am.

Perhaps the reboot type needs a refreshonly parameter? That way it will only initiate a reboot if puppet changed something?

**Comment by ferventcoder** [comment] 2016-12-30 22:26
@johnf this only happens if you define a reboot resource for this.

**Comment by ferventcoder** [comment] 2016-12-30 22:27
https://github.com/puppetlabs/puppetlabs-dsc#handling-reboots-with-dsc - what the docs don't say is that if you don't want the reboot, don't define the resource. HTH

**Comment by johnf** [comment] 2016-12-31 06:03
@ferventcoder I didn't explain myself very well. 

So when things are being set up I do want the reboot. e.g. when installing an active directory feature. I absolutely want the reboot to happen.

Let's say it's a week after deployment though. Nothing has changed but puppet is still running every 30 minute. Now windows update runs and downloads and prepares some updates.

Rather than rebooting during the scheduled window the server will now reboot at the next puppet run even though there will be no changes to the catalog.

Hence my suggestion of a refreshonly support on the resource.

**Comment by ferventcoder** [comment] 2017-01-03 17:58
> Rather than rebooting during the scheduled window the server will now reboot at the next puppet run even though there will be no changes to the catalog.

This sounds more like a bug than expected behavior. Is this because DSC is still passing a reboot message along? Or is this something maybe in our logic for detecting DSC requesting reboots?

**Comment by ferventcoder** [comment] 2017-01-03 18:00
Not sure if closing the ticket was on purpose or accidental? If you filed a JIRA ticket, let's provide a link here so folks know where to go.

**Comment by johnf** [comment] 2017-01-05 04:05
Ahh I did close this accidentally, must have hit the wrong button.

I think xPendingReboot https://github.com/PowerShell/xPendingReboot holds some of the answers.
Notice that it has an option to ignore reboots that come from windows updates.

Where as https://github.com/puppetlabs/puppetlabs-reboot/blob/master/lib/puppet/provider/reboot/windows.rb#L78 reboots if windows updates need one.

**Comment by ferventcoder** [comment] 2017-01-15 03:33
@johnf So are you suggesting a parameter for the reboot module to ignore Windows Updates pending reboots?

**Comment by johnf** [comment] 2017-01-22 21:10
@ferventcoder I think that for a lot of use cases dsc_reboot should only be rebooting things if
a) it detects a reboot is necessary
b) it has been notified to check for reboots

So I'm proposing something like ```refreshonly``` that way if set to true dsc_reboot would only check for pending reboots if it has been notified by another option that has changed.

For example
```
package { 'antivirus_something':
  ensure => latest,
  provider => chocolatey,
  notify => Reboot['dsc_reboot']
}

reboot { 'dsc_reboot' :
    message => 'DSC has requested a reboot',
    when => 'pending',
    refreshonly => true
}
```

That way a reboot can only happen if the package provider installs or upgraded the software. If some manual action has placed the system in a state that requires reboots then it won't reboot.

I think having another parameter called something like ```reason``` could be useful. Perhaps pass it an array.

```
reboot { 'dsc_reboot' :
    message => 'DSC has requested a reboot',
    when => 'pending',
    refreshonly => true,
    reason => ['software', 'rename', 'dsc', 'etc']
}
```

Could also be handy to have a time parameter to only allow reboots at say 3am.

Lots os possibiltities here. Should we move this to https://github.com/puppetlabs/puppetlabs-reboot ?

**Comment by ferventcoder** [comment] 2017-01-23 18:09
> Should we move this to https://github.com/puppetlabs/puppetlabs-reboot ?

That makes sense, however it would be better if we can get you to file a ticket in our ticketing system so we can have a discussion there. https://tickets.puppet.com/browse/MODULES - there is a little Create ticket button in the top row. Fill out as many details as you feel are necessary, then let me know what that ticket is here so we can be sure to carry on this conversation. 

I feel like there are two tickets here. One for DSC and the dsc_reboot resource to use message and refreshonly as a ticket, and followups for enhancements to the Reboot module as a ticket. Would you agree?

**Comment by ferventcoder** [comment] 2017-01-23 18:09
Preemptively closing in advance as tickets will be created to further discuss.

**Closed by ferventcoder** 2017-01-23 18:09 UTC

**Comment by johnf** [comment] 2017-01-24 21:52
Created Jira tickets
* https://tickets.puppetlabs.com/browse/MODULES-4328
* https://tickets.puppetlabs.com/browse/MODULES-4329
* https://tickets.puppetlabs.com/browse/MODULES-4330

**Comment by ferventcoder** [comment] 2017-01-26 22:17
Awesome, thanks!

**Comment by ferventcoder** [comment] 2017-01-26 22:31
Were you going to create a ticket for excluding certain types (windows updates, dsc, etc)? like `exclude => []`

**Comment by johnf** [comment] 2017-01-26 23:14
https://tickets.puppetlabs.com/browse/MODULES-4328 I think you missed that one

**Comment by ferventcoder** [comment] 2017-01-31 21:05
@johnf OH! Now I understand what reason means. It's not obvious, so let's suggest something better. I'll follow up on the ticket.

**Comment by ferventcoder** [comment] 2017-03-02 23:11
@johnf followup - http://samcogan.com/powershell-dsc-xrdsessiondeployment-continuously-reboots/
